name: "Deploy to GitHub Pages"
on: push
env:
  CNAME: "time-calculator.mahdi.pro"
jobs:
  build_and_deploy:
    name: "Build and Deploy"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Add CNAME
        run: echo $CNAME > build/CNAME
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Deploy to GitHub Pages
        run: npx gh-pages -d build
